// web/web-cloudbase-nuxt-template/components/Footer.vue
<template>
  <footer class="footer footer-center p-10 bg-base-200 text-base-content">
    <div>
      <p class="mt-4">基于 Nuxt 3 + CloudBase 构建</p>
      <div class="mt-4">
        <a href="https://github.com/TencentCloudBase/CloudBase-AI-ToolKit" target="_blank" rel="noopener noreferrer">
          <img
            src="https://7463-tcb-advanced-a656fc-1257967285.tcb.qcloud.la/mcp/powered-by-cloudbase-badge.svg"
            alt="Powered by CloudBase"
            class="h-8"
          />
        </a>
      </div>
      <p class="text-xs opacity-50 mt-2">Copyright © {{ new Date().getFullYear() }} - All rights reserved</p>
    </div>
  </footer>
</template>

// web/cloudbase-react-template/src/components/Footer.tsx
const Footer = () => {
  return (
    <footer className="border-t border-gray-200 bg-white py-8">
      <div className="container mx-auto px-4 text-center">
        <div className="flex justify-center gap-4">
          <a
            href="https://github.com/TencentCloudBase/awesome-cloudbase-examples"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 hover:text-gray-900"
          >
            GitHub
          </a>
          <a
            href="https://docs.cloudbase.net"
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-500 hover:text-gray-900"
          >
            文档
          </a>
        </div>
        <p className="mt-4 text-sm text-gray-500">
          基于 React + Vite + CloudBase 构建
        </p>
        <p className="mt-2 text-xs text-gray-400">
          Copyright © {new Date().getFullYear()} - All rights reserved
        </p>
      </div>
    </footer>
  );
};

export default Footer;
